capacities:
  small: &small 6
  medium: &medium 10
  large: &large 12

schedulers:
  simple: &simple 0
  planning: &planning 1

cost_functions:
  random: &random 0
  nearest_neighbour: &nearest_neighbour 1
  better_nearest_neighbour: &better_nearest_neighbour 2
  weighted: &weighted 3

scenarios:

  - name: FACIN
    duration: 43200
    scheduler: [ *simple, *planning ]
    planningHorizon: 5
    cost_function: [ *random, *nearest_neighbour, *better_nearest_neighbour, *weighted ]
    seed: 54TH7hboAG1iOsDIDhJp
    elevators: 4
    capacity: 10
    floors: [ 60, 520, 360, 360, 360, 240, 240, 240]
