capacities:
  small: &small 5
  medium: &medium 8
  large: &large 10

schedulers:
  simple: &simple 0
  planning: &planning 1

cost_functions:
  dummy: &dummy 0
  random: &random 1
  nearest_neighbour: &nearest_neighbour 2
  better_nearest_neighbour: &better_nearest_neighbour 3
  weighted: &weighted 4

scenarios:
  - name: Simple with dummy
    duration: 10000
    scheduler: *simple
    cost_function: *dummy
    seed: 54TH7hboAG1iOsDIDhJp
    elevators: 5
    capacity: *small
    floors: # [ population, lambda ]
      - [ 30, 150 ]
      - [ 30, 300 ]
      - [ 30, 450 ]
      - [ 30, 600 ]
      - [ 30, 500 ]
      - [ 30, 450 ]
      - [ 30, 900 ]

  - name: Simple with random
    duration: 10000
    scheduler: *simple
    cost_function: *random
    seed: 54TH7hboAG1iOsDIDhJp
    elevators: 5
    capacity: *small
    floors: # [ population, lambda ]
      - [ 30, 150 ]
      - [ 30, 300 ]
      - [ 30, 450 ]
      - [ 30, 600 ]
      - [ 30, 500 ]
      - [ 30, 450 ]
      - [ 30, 900 ]

  - name: Simple with nearest_neighbour
    duration: 10000
    scheduler: *simple
    cost_function: *nearest_neighbour
    seed: 54TH7hboAG1iOsDIDhJp
    elevators: 5
    capacity: *small
    floors: # [ population, lambda ]
      - [ 30, 150 ]
      - [ 30, 300 ]
      - [ 30, 450 ]
      - [ 30, 600 ]
      - [ 30, 500 ]
      - [ 30, 450 ]
      - [ 30, 900 ]

  - name: Simple with better_nearest_neighbour
    duration: 10000
    scheduler: *simple
    cost_function: *better_nearest_neighbour
    seed: 54TH7hboAG1iOsDIDhJp
    elevators: 5
    capacity: *small
    floors: # [ population, lambda ]
      - [ 30, 150 ]
      - [ 30, 300 ]
      - [ 30, 450 ]
      - [ 30, 600 ]
      - [ 30, 500 ]
      - [ 30, 450 ]
      - [ 30, 900 ]

  - name: Simple with weighted
    duration: 10000
    scheduler: *simple
    cost_function: *weighted
    seed: 54TH7hboAG1iOsDIDhJp
    elevators: 5
    capacity: *small
    floors: # [ population, lambda ]
      - [ 30, 150 ]
      - [ 30, 300 ]
      - [ 30, 450 ]
      - [ 30, 600 ]
      - [ 30, 500 ]
      - [ 30, 450 ]
      - [ 30, 900 ]