capacities:
  small: &small 5
  medium: &medium 8
  large: &large 10

schedulers:
  simple: &simple 0
  planning: &planning 1

cost_functions:
  dummy: &dummy 0
  random: &random 1
  nearest_neighbour: &nearest_neighbour 2
  better_nearest_neighbour: &better_nearest_neighbour 3
  weighted: &weighted 4

scenarios:
  - name: A
    duration: 10000
    scheduler: *simple
    cost_function: *dummy
    seed: 54TH7hboAG1iOsDIDhJp
    elevators: 5
    capacity: *small
    floors: # [ population, lambda ]
      - [ 300, 150 ]
      - [ 300, 300 ]
      - [ 300, 450 ]
      - [ 300, 600 ]
      - [ 300, 500 ]
      - [ 300, 450 ]
      - [ 300, 900 ]