elevator_config:
  small: &small
    capacity: 5
  medium: &medium
    capacity: 8
  large: &large
    capacity: 10

# dispatchers:
#  0 - dummy
#  1 - random
#  2 - nearest neighbour
#  3 - better nearest neighbour

# cost functions:
#  0 - dummy
#  1 - nearest neighbour

# some seeds
#
# 54TH7hboAG1iOsDIDhJp
# AKx40EMj7do2NA8nrKLn
# 0bhx1tTm923L5uRgFxO8
# sTJMhgDL8rrDOaMXQcOo
# s1j8DZw6Y9TPvo7hiuTY
# UU60LQNjhMa09GZGiVVV
# I0Ayf7VMqvaOAnUQvZCB
# UzTg5GXiQ7SxNa492Y2i
# bP5Y9E7CvVtnBn0qK9fS
# FJtPpvmANuEaBLBaaGB5

scenarios:
  - name: Simple
    duration: 10000
    dispatcher: 2 # random
    cost_function: 0 # dummy
    seed: 54TH7hboAG1iOsDIDhJp
    elevators: 1
    elevator_config: *small
    floors: # [ population, lambda ]
      - [ 300, 150 ]
      - [ 300, 300 ]
      - [ 300, 450 ]
      - [ 300, 600 ]
      - [ 300, 500 ]
      - [ 300, 450 ]
      - [ 300, 900 ]
      - [ 300, 700 ]
      - [ 300, 850 ]
      - [ 300, 800 ]
