capacities:
  small: &small 6
  medium: &medium 10
  large: &large 12

schedulers:
  simple: &simple 0
  planning: &planning 1

cost_functions:
  dummy: &dummy 0
  random: &random 1
  nearest_neighbour: &nearest_neighbour 2
  better_nearest_neighbour: &better_nearest_neighbour 3
  weighted: &weighted 4

scenarios:
  - name: Low-rise
    duration: 10000
    scheduler: [ *simple, *planning ]
    cost_function: [ *dummy, *random, *nearest_neighbour, *better_nearest_neighbour, *weighted ]
    seed: 54TH7hboAG1iOsDIDhJp
    elevators: 2
    capacity: *small
    floors: # [ population, lambda ]
      - [ 30, 2500 ]
      - [ 30, 2500 ]
      - [ 30, 300 ]
      - [ 30, 400 ]
      - [ 30, 100 ]
      - [ 30, 200 ]
      - [ 30, 300 ]
      - [ 30, 400 ]
      - [ 30, 100 ]
      - [ 30, 200 ]
      - [ 30, 300 ]

  - name: High-rise
    duration: 10000
    scheduler: [ *simple, *planning ]
    cost_function: [ *dummy, *random, *nearest_neighbour, *better_nearest_neighbour, *weighted ]
    seed: 54TH7hboAG1iOsDIDhJp
    elevators: 8
    capacity: *medium
    floors: # [ population, lambda ]
      - [ 30, 150 ]
      - [ 30, 300 ]
      - [ 30, 450 ]
      - [ 30, 600 ]
      - [ 30, 150 ]
      - [ 30, 300 ]
      - [ 30, 450 ]
      - [ 30, 600 ]
      - [ 30, 150 ]
      - [ 30, 300 ]
      - [ 30, 450 ]
      - [ 30, 450 ]
      - [ 30, 150 ]
      - [ 30, 300 ]
      - [ 30, 450 ]
      - [ 30, 600 ]
      - [ 30, 150 ]
      - [ 30, 300 ]
      - [ 30, 450 ]
      - [ 30, 600 ]
      - [ 30, 150 ]
      - [ 30, 300 ]
      - [ 30, 450 ]
      - [ 30, 450 ]
      - [ 30, 150 ]
      - [ 30, 300 ]
      - [ 30, 450 ]
      - [ 30, 600 ]
      - [ 30, 150 ]
      - [ 30, 300 ]
      - [ 30, 450 ]
      - [ 30, 600 ]
      - [ 30, 150 ]
      - [ 30, 300 ]
      - [ 30, 450 ]
      - [ 30, 450 ]
      - [ 30, 300 ]
      - [ 30, 450 ]
      - [ 30, 450 ]

  # - name: Skyscraper
  #   duration: 10000
  #   scheduler: [ *simple, *planning ] # [ *simple, *planning ]
  #   cost_function: [ *nearest_neighbour ] # [ *dummy, *random, *nearest_neighbour, *better_nearest_neighbour, *weighted ]
  #   seed: 54TH7hboAG1iOsDIDhJp
  #   elevators: 16
  #   capacity: *large
  #   floors: # [ population, lambda ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 600 ]
  #     - [ 30, 150 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 300 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]
  #     - [ 30, 450 ]