poisson:
  seed: Semente sementosa sementuda!
  population: 150
  event_interval: 50
  experiments: 10000

elevator_config:
  small: &small
    capacity: 5
  medium: &medium
    capacity: 8
  large: &large
    capacity: 10

scenarios:
  - name: Simple
    elevators: 2
    elevator_config: *small
    population: [ 5, 5, 5, 5, 5, 5 ]
    dispatcher: 0
    cost_function: 0

  # - name: Scenario 01
  #   elevators: 2
  #   elevator_config: *small
  #   population: [ 30, 10, 10, 10, 10 ]
  #   dispatcher: 0
  #   cost_function: 0

  # - name: Scenario 02
  #   elevators: 3
  #   capacity: 8
  #   elevator_config: *medium
  #   population: [ 50, 30, 30, 30, 30, 30, 30, 30 , 30, 30]
  #   dispatcher: 1
  #   cost_function: 1

  # - name: Scenario 03
  #   elevators: 8
  #   elevator_config: *large
  #   population: [ 160, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80 ]
  #   dispatcher: 2
  #   cost_function: 1