elevator_config:
  small: &small
    capacity: 5
  medium: &medium
    capacity: 8
  large: &large
    capacity: 10

# dispatchers:
#  0 - dummy
#  1 - random
#  2 - nearest neighbour
#  3 - better nearest neighbour

# cost functions:
#  0 - dummy
#  1 - nearest neighbour

scenarios:
  - name: Simple
    duration: 30
    dispatcher: 1 # random
    cost_function: 0 # dummy
    seed: Semente sementosa sementuda!
    elevators: 1
    elevator_config: *small
    floors: # [ population, lambda ]
      - [ 3, 1 ]
      - [ 3, 10 ]
      - [ 3, 15 ]
      - [ 3, 18 ]
      - [ 3, 20 ]
