elevator_config:
  small: &small
    capacity: 5
  medium: &medium
    capacity: 8
  large: &large
    capacity: 10

scenarios:
  - name: Test Scenario
    elevators: 2
    elevator_config: *small
    population: [ 10, 10, 10, 10, 10 ]
    dispatcher: 0
    cost_function: 0